### PR TITLE
INTEGER PRIMARY KEY is an alias for ROWID in SQLite3

### PR DESCRIPTION
**Pull request by ichiban**
https://github.com/xo/xo/pull/153

### CODE REVIEW

**Comment by turnkey-commerce** [comment]
Thanks for submitting this PR.  When I reviewed it I realized there is a problem in that the code within the models folder is generated by "gen.sh" in the root folder and it has that line in there about it being generated and not to edit. The original xo operates on kind of like an"Inception" concept in that it uses itself to first query the databases to generate the base models.

I'm not sure if there is an easy way to do what you're trying to do with the gen.sh, but  I think there may be another strategy which would be to modify the loaders/sqlite.go (which is open for edit) and use models.SqAutoIncrements that is loaded in the first step to identify that it is a primary key in this classification. 

Sorry for the confusion about it and I will add some Contributing guidelines to make the contributors aware of this fact.  I ran into the same issue on the first PR that I made to xo.

**Comment by turnkey-commerce** [comment]
Referencing Issue #2

**Comment by turnkey-commerce** [comment]
On further review I think this can be boiled down to a two-line change (with comment) in loaders/sqlite.go to the NotNull property setting around line 189:

```
	// fix columns
	var cols []*models.Column
	for _, row := range rows {
		cols = append(cols, &models.Column{
			FieldOrdinal: row.FieldOrdinal,
			ColumnName:   row.ColumnName,
			DataType:     row.DataType,
			// It's not null if so defined in the column or if it's a primary key.
			NotNull: row.NotNull || row.PkColIndex != 0,
			IsPrimaryKey: row.PkColIndex != 0,
		})
	}
```
In my testing this works fine and allows other columns besides PK's to be nullable. Can you please verify it does what it should do and if so resubmit the PR and squash the commit to just include this?

**Comment by ichiban** [comment]
@turnkey-commerce My bad. Obviously change has to be made in `loaders/sqlite.go`. 
I see, "Inception." Thank you for a good "kick!" You can reject this PR since it takes a wrong approach.

As far as I know, INTEGER PRIMARY KEY is a very special case and it doesn't apply to tables with compound primary key.

Let's take an example of a table with compound primary key:

```sql
CREATE TABLE users (
       email TEXT,
       old_id INTEGER,
       PRIMARY KEY (email, old_id)
);
```

My change generates this and it doesn't trigger INTEGER PRIMARY KEY special case so both members of the primary key are nullable.

```go
// User represents a row from 'users'.
type User struct {
	Email sql.NullString `json:"email"`  // email
	OldID sql.NullInt64  `json:"old_id"` // old_id

	// xo fields
	_exists, _deleted bool
}
```

With https://github.com/turnkey-commerce/gendal/pull/1#issuecomment-421816976, it'll generate this which mistakenly makes them non-nullable.

```go
// User represents a row from 'users'.
type User struct {
	Email string `json:"email"`  // email
	OldID int    `json:"old_id"` // old_id

	// xo fields
	_exists, _deleted bool
}
```

**Comment by turnkey-commerce** [comment]
Closed in favor of other approach in #3.

**Pull request closed without merging**
